### ISSUE TITLE
Top Stories Widget not updating

### ISSUE THREAD

**Issue by gauripadbidri** [jtsternberg/Google-Analytics-Top-Content-Widget#2]
I am using "Top Content Widget" in my site on ALL pages. I am also using the "Nginx Helper" plugin to cache my pages. When a page is cached does the plugin code NOT get invoked ? As I observe the same..Hence, the widget does not update and I see stale stories...I also saw the FILTER fix that has been checked in to GITHUB...But, seems like that too does not help....
Can anyone help me on this one ? Thanks !

**Comment by jtsternberg** [comment]
Yes, if you cache your pages, the shortcode output will also be cached. Also, the shortcode and widget does its own 24hr caching so that we are not continually hitting the Google Analytics API.

**Comment by gauripadbidri** [comment]
Thanks for your response...But, we have been using this plugin since the Version 1.5.7 which used OAuth (where the pages used to display updated stories and view counts)..May be Google Dashboard was taking care of purging cache (as we used to set the Cache Timeout) after the Cache Timout would trigger ? which is now not configurable ?

**Comment by jtsternberg** [comment]
Sorry, but I'm not sure I understand the question.

**Comment by gauripadbidri** [comment]
I meant what if I want to update the widget every 15 - 20 mins even if the page is cached ? Is it possible ? How ? Because with the previous version (1.5.7 which had a dependency on GA Dashboard), we could configure cache timeout (assume 15 mins) which would reflect updated Top Stories after the set interval i.e. 15 mins.

**Comment by jtsternberg** [comment]
I see.. It's not currently possible (with the plugin on wordpress.org), nor would have ever been. Even if you modified the cache timeout w/ GA Dashboard, the widget still cached its own values for 24 hours. The next version that will be released (which you can get right now via this repo) will have a filter available in order to modify the cache-timeout (https://github.com/jtsternberg/Google-Analytics-Top-Content-Widget/commit/7f9a607375197b84f10a1e8bb252307eab00a8c1). But even with that, if your page is cached with varnish, those values would not update until your varnish cache expires.
